export const data = [
    {
        id: 1,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 2,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 3,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 4,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 5,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 6,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 7,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 8,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 9,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 10,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 11,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 12,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 13,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 14,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 15,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 16,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 17,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 18,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 19,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
    {
        id: 20,
        source: 'Source',
        customerName: 'Customer Name',
        customerEmail: 'Customer Email',
        amount: 'Amount',
        requestDate: 'Request Date',
        status: 'Status',
    },
]