export const columns = [
  "Transaction ID",
  "Source",
  "Customer Name",
  "Customer Email",
  "Amount",
  "Request Date",
  "Status",
];

export const tableData = [
  {
    id: 1,
    transactionID: 'GB124QWERTY12346',
    source: "GTB",
    customerName: "Mike Owen",
    customerEmail: "0223337281",
    amount: "$230.00",
    requestDate: "24.08.2021",
    status: "Pending",
  },
  {
    id: 2,
    transactionID: 'CB328ABCEDF23416',
    source: "UBA",
    customerName: "Steve O'Shassy",
    customerEmail: "0982764829",
    amount: "$480.00",
    requestDate: "22.08.2021 ",
    status: "Successful",
  },
  {
    id: 3,
    transactionID: 'GB124QWERTY12346',
    source: "GTB",
    customerName: "Mike Owen",
    customerEmail: "0223337281",
    amount: "$230.00",
    requestDate: "24.08.2021",
    status: "Pending",
  },
  {
    id: 4,
    transactionID: 'GB124QWERTY12346',
    source: "GTB",
    customerName: "Mike Owen",
    customerEmail: "0223337281",
    amount: "$230.00",
    requestDate: "24.08.2021",
    status: "Pending",
  },
  {
    id: 5,
    transactionID: 'GB124QWERTY12346',
    source: "FCMB",
    customerName: "Ayomide",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 6,
    transactionID: 'GB124QWERTY12346',
    source: "UBA",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 7,
    transactionID: 'GB124QWERTY12346',
    source: "ZENITH",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 8,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 9,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 10,
    source: "Ayinde",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 11,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 12,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 13,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 14,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 15,
    source: "Source",
    customerName: "Kelly",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 16,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 17,
    source: "Source",
    customerName: "Precious",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 18,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 19,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 20,
    source: "Source",
    customerName: "Jimi",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 21,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 22,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 23,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 24,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 25,
    source: "Source",
    customerName: "Soundmind",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 26,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 27,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 28,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 29,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 30,
    source: "Source",
    customerName: "Isreal",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 31,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 32,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 33,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 34,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 35,
    source: "Source",
    customerName: "favor",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 36,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 37,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 38,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 39,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 40,
    source: "Source",
    customerName: "Tobi",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 41,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 42,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 43,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 44,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 45,
    source: "Source",
    customerName: "Ebube",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 46,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 47,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 48,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 49,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 50,
    source: "Source",
    customerName: "Frank",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 51,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 52,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 53,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 54,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 55,
    source: "Source",
    customerName: "Keanu Reaves",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 56,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 57,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 58,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 59,
    source: "Source",
    customerName: "Customer Name",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
  {
    id: 60,
    source: "Source",
    customerName: "Christoper Nolan",
    customerEmail: "Customer Email",
    amount: "Amount",
    requestDate: "Request Date",
    status: "Status",
  },
];
